## Autogenerated from D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/tools/clang/test/lit.site.cfg.py.in
## Do not edit!

import sys

config.llvm_src_root = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm"
config.llvm_obj_root = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/Release"
config.llvm_tools_dir = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/Release/./bin"
config.llvm_libs_dir = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/Release/./lib"
config.llvm_shlib_dir = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/Release/./bin"
config.llvm_plugin_ext = ".dll"
config.lit_tools_dir = ""
config.clang_obj_root = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/Release/tools/clang"
config.clang_src_dir = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/tools/clang"
config.clang_tools_dir = "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/Release/./bin"
config.host_triple = "i686-pc-windows-msvc"
config.target_triple = "i686-pc-windows-msvc"
config.host_cxx = "D:/SoftWare/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86/cl.exe"
config.llvm_use_sanitizer = ""
config.have_zlib = 0
config.clang_arcmt = 1
config.clang_default_cxx_stdlib = ""
config.clang_staticanalyzer = 1
config.clang_staticanalyzer_z3 = ""
config.clang_examples = 0
config.enable_shared = 0
config.enable_backtrace = 1
config.enable_experimental_new_pass_manager = 0
config.host_arch = "AMD64"
config.python_executable = "D:/SoftWare/Python385/python.exe"
config.use_z3_solver = lit_config.params.get('USE_Z3_SOLVER', "")
config.has_plugins = 0

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.clang_tools_dir = config.clang_tools_dir % lit_config.params
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_shlib_dir = config.llvm_shlib_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "D:/SoftWareDemoStudy/cclsBuild/llvm_build/llvm/tools/clang/test/lit.cfg.py")
